corpora:
    # ilci:
    #     splits: ['train']
    #     # langs: [ 'en', 'hi',  'ta', 'te', 'ml', 'ur', 'bn']
    #     langs: ['en', 'hi']
        # langs: ['en', 'hi']
        # wat-ilmpc:
        # wat-splits: ['dev']
        # wat-langs: ['en', 'ta']
    # iitb-hi-en:
    #     splits: ['train', 'dev', 'test']
    #     langs: ['en', 'hi']
    # wat-ilmpc:
    #     splits: ['train', 'dev', 'test']
    #     # langs: [ 'en', 'hi',  'ta', 'te', 'ml', 'ur', 'bn']
    #     langs: ['en', 'ta']
    # national-newscrawl:
    #     splits: ['train']
    #     langs: ['en', 'hi']
    ufal-en-tam:
        splits: ['train', 'test', 'dev']
        langs: ['en', 'ta']
    # mechturk-en-te:
    #     splits: ['train', 'dev', 'test']
    #     langs: ['en', 'te']
    # complete-en-te:
    #     splits: ['train', 'dev', 'test']
    #     langs: ['en', 'te']
    # pretrain-en-tam:
    #     splits: ['train', 'dev']
    #     langs: ['en', 'ta']

dictionary:
    src: '/root/src/ilmulti/resources/fairseq-dictionaries/vocab.dict'
    tgt: '/root/src/ilmulti/resources/fairseq-dictionaries/vocab.dict'

hard_coded_dict: {
    'en': 4000,
    'ta': 4000
}
